#!/bin/sh

die (){
    echo error building
    exit 1
}

CXX=${CXX-c++}

if [ $# == 0 ]; then
    echo "usage: twrun [file.cpp] [program args...]"
    exit 1
fi

$CXX -std=c++11 -o .tmp.bin -xc++ $1 -ltwombly `pkg-config --cflags twombly` || die
shift
./.tmp.bin $@ && rm .tmp.bin
